<?php
    return [
        'admin' => [
            'create-language', // table langauges
            'read-language',
            'update-language',
            'delete-language',
            'show-language',
            'create-city', // table cities
            'read-city',
            'update-city',
            'delete-city',
            'show-city',
            'create-country', // table countries
            'read-country',
            'update-country',
            'delete-country',
            'show-country',
            'create-zipcode', // table zipcodes
            'read-zipcode',
            'update-zipcode',
            'delete-zipcode',
            'show-zipcode',
            'create-tag', // table tags
            'read-tag',
            'update-tag',
            'delete-tag',
            'show-tag',
            'create-pricing-plan', // table pricing_plans
            'read-pricing-plan',
            'update-pricing-plan',
            'delete-pricing-plan',
            'show-pricing-plan',
            'create-user', // table users
            'read-user',
            'update-user',
            'delete-user',
            'show-user',
        ],
        'author' => [
            'read-language',
            'show-language',
            'read-city',
            'show-city',
            'read-country',
            'show-country',
            'read-zipcode',
            'show-zipcode',
            'read-tag',
            'show-tag',
            'read-pricing-plan',
            'show-pricing-plan',
            'read-user',
            'show-user',
        ],
        'reviewer' => [
            'read-language',
            'show-language',
            'read-city',
            'show-city',
            'read-country',
            'show-country',
            'read-zipcode',
            'show-zipcode',
            'read-tag',
            'show-tag',
            'read-pricing-plan',
            'show-pricing-plan',
            'read-user',
            'show-user',
        ],
        'sponsor' => [
            'read-language',
            'show-language',
            'read-city',
            'show-city',
            'read-country',
            'show-country',
            'read-zipcode',
            'show-zipcode',
            'read-tag',
            'show-tag',
            'read-pricing-plan',
            'show-pricing-plan',
            'read-user',
            'show-user',
        ],
        'customer' => [
            'read-language',
            'show-language',
            'read-city',
            'show-city',
            'read-country',
            'show-country',
            'read-zipcode',
            'show-zipcode',
            'read-tag',
            'show-tag',
            'read-pricing-plan',
            'show-pricing-plan',
            'read-user',
            'show-user',
        ],
        'guest' => [
            'read-language',
            'show-language',
            'read-city',
            'show-city',
            'read-country',
            'show-country',
            'read-zipcode',
            'show-zipcode',
            'read-tag',
            'show-tag',
            'read-pricing-plan',
            'show-pricing-plan',
            'read-user',
            'show-user',
        ],
    ];
